import os
import re
from typing import List, Dict
from dotenv import load_dotenv
from supabase import create_client, Client
from pydantic import BaseModel, Field
from google import genai
from google.genai import types
import discord
import threading
from http.server import SimpleHTTPRequestHandler, HTTPServer

# =====================================================================
# PHASE 1: INITIALIZATION & SERVER HOOKS
# =====================================================================
load_dotenv()

SUPABASE_URL: str = os.getenv("SUPABASE_URL")
SUPABASE_KEY: str = os.getenv("SUPABASE_KEY")
GEMINI_API_KEY: str = os.getenv("GEMINI_API_KEY")
DISCORD_TOKEN: str = os.getenv("DISCORD_TOKEN")

# Dynamic greeting setup pulled directly from cloud configuration
CUSTOM_GREETING: str = os.getenv(
    "REGISTRATION_GREETING", 
    "🛡️ **Registration Started!**\n\nPlease reply with your **Team Name** and **Leader's Phone Number** separated by a comma.\n*Example: Team Solitude, 9876543210*"
)

if not all([SUPABASE_URL, SUPABASE_KEY, GEMINI_API_KEY, DISCORD_TOKEN]):
    raise ValueError("CRITICAL ERROR: Missing configuration strings inside the .env file.")

supabase_client: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
ai_client = genai.Client(api_key=GEMINI_API_KEY)

intents = discord.Intents.default()
intents.message_content = True 
discord_gateway_client = discord.Client(intents=intents)

# Short-term session memory mapping for state isolation
REGISTRATION_STATES: Dict[str, dict] = {}


# =====================================================================
# PHASE 2: PARSING BLOCK SCHEMAS (DATA VALIDATION MATRIX)
# =====================================================================
class SimplePlayerNode(BaseModel):
    """Rigid blueprint structure for an individual team player."""
    riot_id: str = Field(description="The complete In-Game Name / Riot ID string (e.g., Phantom#999).")
    rank: str = Field(description="The competitive rank of the player (e.g., Gold 2).")

class ExtractedRosterData(BaseModel):
    """Comprehensive validation blueprint forcing the AI to format array nodes uniformly."""
    players: List[SimplePlayerNode] = Field(description="Array list of all 5 parsed players.")
    is_valid: bool = Field(description="Set to True ONLY if at least 5 distinct players with Riot IDs and ranks are found.")
    error_message: str = Field(description="If is_valid is False, state clearly what went wrong with the roster text layout.")


# =====================================================================
# PHASE 3: DATABASE RELATIONAL LAYERS (FLAT COLUMN MATRIX)
# =====================================================================
def commit_simplified_team_to_db(captain_id: str, team_name: str, phone_number: str, roster_list: List[SimplePlayerNode]) -> bool:
    """Inserts team info with leader phone number, takes the key, and writes a flat 1-player-per-column row to players."""
    
    # 1. Store Header Info inside the 'teams' table
    team_payload = {
        "team_name": team_name,
        "captain_discord_id": captain_id,
        "leader_phone": phone_number
    }
    team_response = supabase_client.table("teams").insert(team_payload).execute()
    
    if not team_response.data:
        raise RuntimeError("Database tracking team insertion rejected.")
        
    # Grab the unique team_id key string generated by Supabase
    inserted_team_id = team_response.data[0]["team_id"]

    # 2. Flat pack exactly 1 player account + rank string per assigned text column
    player_payload = {
        "team_id": inserted_team_id,
        "player_1": f"{roster_list[0].riot_id} - {roster_list[0].rank}",
        "player_2": f"{roster_list[1].riot_id} - {roster_list[1].rank}",
        "player_3": f"{roster_list[2].riot_id} - {roster_list[2].rank}",
        "player_4": f"{roster_list[3].riot_id} - {roster_list[3].rank}",
        "player_5": f"{roster_list[4].riot_id} - {roster_list[4].rank}"
    }
    
    # Commit the clean layout straight into the players table row matrix
    supabase_client.table("players").insert(player_payload).execute()
    return True


# =====================================================================
# PHASE 4: AGENTIC TOKEN EXTRACTION ROUTINES (LLM HANDSHAKE)
# =====================================================================
def parse_text_roster_list(user_raw_text: str) -> ExtractedRosterData:
    """Uses Gemini 2.5 Flash to automatically extract clean structures from raw human lists."""
    system_instruction = """
    You are the specialized Roster Evaluator. Your sole job is to clean and extract player accounts and ranks from a text list.
    
    Rules:
    1. Look for the player's In-Game Name / Riot ID. Ensure it contains a '#' separator tag.
    2. Extract their competitive rank mentioned next to or near their name.
    3. If there are fewer than 5 valid players parsed, set is_valid to False and write a helpful error_message.
    """
    response = ai_client.models.generate_content(
        model='gemini-2.5-flash',
        contents=user_raw_text,
        config=types.GenerateContentConfig(
            system_instruction=system_instruction,
            response_mime_type="application/json",
            response_schema=ExtractedRosterData,
            temperature=0.1
        ),
    )
    return ExtractedRosterData.model_validate_json(response.text)


# =====================================================================
# PHASE 5: LIVE GATEWAY NETWORK INTERCEPTORS (DISCORD LOOPS)
# =====================================================================
@discord_gateway_client.event
async def on_ready():
    print(f"\n🤖 Production Flat-Column Registration Engine Live!")
    print(f"Connected to Gateway as: {discord_gateway_client.user}")

@discord_gateway_client.event
async def on_message(message):
    if message.author == discord_gateway_client.user:
        return

    user_id = str(message.author.id)

    # Command Initialization Trigger Hook
    if message.content.startswith("!register_team"):
        if user_id in REGISTRATION_STATES:
            await message.channel.send("⚠️ You are already running a registration profile interface! Type `!cancel` to drop it.")
            return
            
        REGISTRATION_STATES[user_id] = {
            "step": "AWAITING_TEAM_AND_PHONE",
            "team_name": "",
            "phone_number": ""
        }
        
        await message.channel.send(CUSTOM_GREETING)
        return

    # Cancel Catch Escape Hatch
    if message.content == "!cancel" and user_id in REGISTRATION_STATES:
        del REGISTRATION_STATES[user_id]
        await message.channel.send("🛑 *Registration process dropped. Session memory cleaned.*")
        return

    # Multiphase Dynamic Interceptor Matrix
    if user_id in REGISTRATION_STATES:
        session = REGISTRATION_STATES[user_id]

        # STEP 1: Process and Parse Team Name + Phone Number together
        if session["step"] == "AWAITING_TEAM_AND_PHONE":
            raw_input = message.content.strip()
            
            if "," not in raw_input:
                await message.channel.send("⚠️ Please provide both the **Team Name** and **Phone Number** separated by a comma!\n*Example: Team Vandal, 9876543210*")
                return
                
            parts = raw_input.split(",", 1)
            team_name = parts[0].strip()
            phone_num = parts[1].strip()
            
            # Clean up potential extra spaces or characters in the phone string
            phone_digits = re.sub(r"\D", "", phone_num)
            
            if len(team_name) < 2:
                await message.channel.send("⚠️ Team name too short! Please provide a valid team name:")
                return
                
            if len(phone_digits) < 8:
                await message.channel.send("⚠️ That doesn't look like a valid phone number. Please check and try again:")
                return
                
            session["team_name"] = team_name
            session["phone_number"] = phone_digits
            session["step"] = "AWAITING_ROSTER_TEXT"
            
            guide_prompt = (
                f"✅ **Team details logged!**\n"
                f"• Team Name: `{team_name}`\n"
                f"• Contact Phone: `{phone_digits}`\n\n"
                f"📝 **Roster Collection Menu:**\n"
                f"Please type out your **5 players** with their **Riot ID** and **Rank** on separate lines. "
                f"Example layout format:\n"
                f"```text\n"
                f"1. ViperBait#4411 - Platinum 1\n"
                f"2. SpikeRunner#9988 - Diamond 3\n"
                f"3. JettDiff#0022 - Silver 2\n"
                f"4. NeonMain#5544 - Immortal 2\n"
                f"5. ReynaClutch#1122 - Gold 3\n"
                f"```"
            )
            await message.channel.send(guide_prompt)
            return

        # STEP 2: Process text array list block using Gemini Core
        if session["step"] == "AWAITING_ROSTER_TEXT":
            await message.channel.send("⏳ *Processing and verifying your roster list...*")
            
            # Fire parsing routine
            try:
                parsed_roster = parse_text_roster_list(message.content)
            except Exception as ai_error:
                print(f"CRITICAL AI FAILURE: {ai_error}")
                # 💡 TEMP AI DEBUG LINE
                await message.channel.send(f"❌ **Internal AI Parse Error:**\n```text\n{str(ai_error)}\n```")
                del REGISTRATION_STATES[user_id]
                return
            
            if parsed_roster.is_valid:
                try:
                    # Pass the parsed strings and the phone numbers safely into the relational tables
                    commit_simplified_team_to_db(user_id, session["team_name"], session["phone_number"], parsed_roster.players)
                    await message.channel.send(
                        f"🎉 **Registration Successful!**\n"
                        f"🛡️ Team **'{session['team_name']}'** has been successfully cataloged.\n"
                        f"Your registration details are locked in for the tournament!"
                    )
                except Exception as db_error:
                    err_str = str(db_error)
                    if "23505" in err_str or "teams_team_name_key" in err_str:
                        await message.channel.send(f"⚠️ **Registration Failed:** The team name `{session['team_name']}` is already registered!")
                    else:
                        # 💡 TEMP DATABASE DEBUG LINE
                        await message.channel.send(f"❌ **Internal Database Error:**\n```text\n{err_str}\n```")
                    print(f"Database insertion exception: {db_error}")
                finally:
                    del REGISTRATION_STATES[user_id]
            else:
                await message.channel.send(
                    f"⚠️ **Roster Verification Failed:** {parsed_roster.error_message}\n"
                    f"Please re-enter your 5-player list following the correct structure:"
                )


# =====================================================================
# RENDER PORTS COMPLIANCE BACKEND DUMMY DAEMON
# =====================================================================
def run_dummy_server():
    """Spins up a lightweight background web server to pass Render web traffic port scans."""
    port = int(os.environ.get("PORT", 10000))
    server = HTTPServer(('0.0.0.0', port), SimpleHTTPRequestHandler)
    server.serve_forever()

if __name__ == "__main__":
    threading.Thread(target=run_dummy_server, daemon=True).start()
    discord_gateway_client.run(DISCORD_TOKEN)